eureka:
  client:
    serviceUrl:
      defaultZone: http://naming-server:8761/eureka
  instance:
    preferIpAddress: true
    hostname: localhost
    lease-renewal-interval-in-seconds: 30
spring:
  rabbitmq:
    host: rabbitmq
  zipkin:
    baseUrl: http://zipkin-server:9411
    sender:
      type: rabbit
rabbit:
  uri: amqp://guest:guest@rabbitmq:5672