eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:
    serviceUrl:
      # defaultZone: http://localhost:8761/eureka
      defaultZone: http://naming-server:8761/eureka
spring:
  rabbitmq:
    host: rabbitmq
  zipkin:
    baseUrl: http://zipkin-server:9411
    sender:
      type: rabbit
rabbit:
  uri: amqp://guest:guest@rabbitmq:5672