rest:
  currency-exchange:
    url: http://currency-exchange:8000/currency-exchange/from/{from}/to/{to}
    main-url: localhost:8000
eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://naming-server:8761/eureka
spring:
  zipkin:
    baseUrl: http://zipkin-server:9411