version: "3.8"
services:
  currency-exchange:
    image: 'com.microservice/currency-exchange-service:0.0.1-SNAPSHOT'
    container_name: currency-exchange
    ports:
      - '8000:8000'
    networks:
      - currency-network
    depends_on:
      - naming-server
    # env_file:
    #   - ./mysql.env

  currency-conversion:
    image: 'com.microservice/currency-conversion-service:0.0.1-SNAPSHOT'
    container_name: currency-conversion
    ports:
      - '8100:8100'
    depends_on:
      - naming-server
    networks:
      - currency-network
  naming-server:
    image: 'com.microservice/naming-server:0.0.1-SNAPSHOT'
    container_name: naming-server
    ports:
      - '8761:8761'
    networks:
      - currency-network
  api-gateway:
    image: 'com.microservice/api-gateway:0.0.1-SNAPSHOT'
    container_name: api-gateway
    ports:
      - '8765:8765'
    depends_on:
      - naming-server
    networks:
      - currency-network
  # zipkin-server:
  #   image: openzipkin/zipkin:latest
  #   ports:
  #     - '9411:9411'
  #   networks:
  #     - currency-network
  #   depends_on:
  #     - rabbitmq
  #   restart:
  #     always
networks:
  currency-network: